# Generated by Django 4.2.15 on 2026-07-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="failed_login_attemps",
            new_name="failed_login_attempts",
        ),
    ]
